### PR TITLE
Release 0.17

### PR DESCRIPTION
**Pull request by tsibley**

### CODE REVIEW

**Comment by tsibley** [comment]
Replaces PR #3.

**Comment by tsibley** [comment]
Ping? /cc @alexmv @sartak

**Comment by alexmv** [comment]
Hm — I see test fails:

```
Test Summary Report
-------------------
t/04-scope.t   (Wstat: 1792 Tests: 37 Failed: 7)
  Failed tests:  19, 21, 23, 25, 31, 33, 37
  Non-zero exit status: 7
t/07-frame.t   (Wstat: 512 Tests: 55 Failed: 2)
  Failed tests:  40, 53
  Non-zero exit status: 2
t/09-args.t    (Wstat: 256 Tests: 26 Failed: 1)
  Failed test:  26
  Non-zero exit status: 1
t/11-warn.t    (Wstat: 256 Tests: 7 Failed: 1)
  Failed test:  7
  Non-zero exit status: 1
Files=15, Tests=375,  7 wallclock secs ( 0.22 usr  0.02 sys +  6.22 cusr  0.78 csys =  7.24 CPU
```

**Comment by karenetheridge** [comment]
Redundant -- see PR #5.

**Pull request closed without merging**
